server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_test
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    hibernate:
      ddl-auto: update
